name: CI - ChatBot Itau

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checar o repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2️⃣ Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Rodar Lint (flake8)
      - name: Lint do projeto
        run: |
          pip install flake8
          flake8 app/

      # 5️⃣ Rodar testes unitários
      - name: Rodar testes unitários
        run: |
          pip install pytest
          pytest -v
